version: '3.8'

services:
  app:
    image: node:18
    ports:
      - "3000:3000"
    working_dir: /usr/src/app  
    volumes:
      - .:/usr/src/app 
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    command: npm start

  test:
    image: node:18 
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    command: npm test
